name: Run TestSweets Tests

on:
  push:
  workflow_dispatch:

jobs:
  testsweets_tests:
    runs-on: macos-latest

    outputs:
      built-apk: ${{ steps.buildApk.outputs.apkPath }}


    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: 'Set up JDK'
        uses: 'actions/setup-java@v1'
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"

      - name: 'Get all packages'
        run: flutter pub get

      - name: 'Build APK'
        id: buildApk
        run: 'flutter build apk --debug


      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      
      - name: Install TestSweets
        run: |
          brew tap filledstacks/tap
          brew install testsweets
      
      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          script: ./gradlew connectedCheck
      
      - name: Run TestSweets Test
        run: testsweets run -p qA5ua2TOgxBtMGcSVBGE -a build/app/outputs/flutter-apk/app-debug.apk
